//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 0c8d4f2b-c319-47bb-a18d-6f9bfa09ff49 aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:de319de4-e66e-49cb-8acc-e06a3867b244";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "shoppingcart-userfiles-mobilehub-1030480558";
}
